"""empty message

Revision ID: 02c60ebeaa7f
Revises: 28d2e22e7e51
Create Date: 2025-06-13 17:27:05.304298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02c60ebeaa7f'
down_revision = '28d2e22e7e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_message', mysql.LONGTEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('failed_message')

    # ### end Alembic commands ###
