"""empty message

Revision ID: 443e1abf6910
Revises: c6689b7e57a5
Create Date: 2025-06-14 13:56:56.605187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '443e1abf6910'
down_revision = 'c6689b7e57a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_article_html', mysql.LONGTEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('final_article_html')

    # ### end Alembic commands ###
