"""empty message

Revision ID: 7b88a2d12284
Revises: bb47b65a38c0
Create Date: 2025-06-17 02:49:58.602318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b88a2d12284'
down_revision = 'bb47b65a38c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gen_final_article_content', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('gen_final_article_html', mysql.LONGTEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('gen_final_article_html')
        batch_op.drop_column('gen_final_article_content')

    # ### end Alembic commands ###
