"""empty message

Revision ID: 84aa84cd3e71
Revises: 7b88a2d12284
Create Date: 2025-06-17 12:24:24.722068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84aa84cd3e71'
down_revision = '7b88a2d12284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_intent', mysql.LONGTEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('search_intent')

    # ### end Alembic commands ###
