"""empty message

Revision ID: bb47b65a38c0
Revises: e1eaf1f3c475
Create Date: 2025-06-16 22:46:38.962503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb47b65a38c0'
down_revision = 'e1eaf1f3c475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loading_text', mysql.LONGTEXT(), nullable=True))
        batch_op.drop_column('step')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('loading_text')

    # ### end Alembic commands ###
