"""empty message

Revision ID: c6689b7e57a5
Revises: xxxx
Create Date: 2025-06-14 00:30:00.747766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6689b7e57a5'
down_revision = 'xxxx'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seo_description', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('url_example', mysql.LONGTEXT(), nullable=True))
        batch_op.add_column(sa.Column('main_image_option', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sub_images_option', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('sub_images_option')
        batch_op.drop_column('main_image_option')
        batch_op.drop_column('url_example')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')

    # ### end Alembic commands ###
