"""empty message

Revision ID: fd40944bb71b
Revises: 84aa84cd3e71
Create Date: 2025-06-18 00:50:49.440842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd40944bb71b'
down_revision = '84aa84cd3e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_description', mysql.LONGTEXT(), nullable=True))
        batch_op.alter_column('seo_title',
               existing_type=mysql.VARCHAR(length=100),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
        batch_op.drop_column('seo_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_description', mysql.LONGTEXT(), nullable=True))
        batch_op.alter_column('seo_title',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('article_description')

    # ### end Alembic commands ###
