"""add pending status

Revision ID: xxxx
Revises: 02c60ebeaa7f
Create Date: 2025-06-13 17:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'xxxx'  # Alembic 会自动生成
down_revision = '02c60ebeaa7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('in_progress', 'completed', 'failed'),
               type_=mysql.ENUM('pending', 'in_progress', 'completed', 'failed'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'in_progress', 'completed', 'failed'),
               type_=mysql.ENUM('in_progress', 'completed', 'failed'),
               existing_nullable=False)

    # ### end Alembic commands ### 